// generated by Fast Light User Interface Designer (fluid) version 1.0100

#ifndef about_h
#define about_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Return_Button.H>
#include "PixWid.h"

class AboutBox {
public:
  AboutBox();
  Fl_Window *win;
  Fl_Box *state;
  Fl_Box *note;
  Fl_Return_Button *ok_button;
  PixWid *icon;
  void run();
  ~AboutBox();
};
#endif
