// generated by Fast Light User Interface Designer (fluid) version 1.0100

#include "about.h"
// Quat - A 3D fractal generation program
// Copyright (C) 1997-2000 Dirk Meyer
// (email: dirk.meyer@studserv.uni-stuttgart.de)
// mail:  Dirk Meyer
//        Marbacher Weg 29
//        D-71334 Waiblingen
//        Germany
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "icon.xpm"

AboutBox::AboutBox() {
  Fl_Window* w;
  { Fl_Window* o = win = new Fl_Window(418, 360, "About Quat");
    w = o;
    o->user_data((void*)(this));
    { Fl_Box* o = state = new Fl_Box(150, 15, 250, 15);
      o->labelfont(1);
      o->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
    }
    { Fl_Box* o = new Fl_Box(150, 70, 235, 45, "A 3D Fractal Generation Program\nCopyright (C) 1997-2002 Dirk Meyer\ndirk.mey\
er@@studserv.uni-stuttgart.de");
      o->labelsize(12);
      o->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
    }
    { Fl_Box* o = new Fl_Box(25, 115, 390, 45, "http://www.physcip.uni-stuttgart.de/phy11733/index_e.html\nQuat Mailing List:\
 http://groups.yahoo.com/group/quat/");
      o->labelsize(12);
      o->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
    }
    { Fl_Box* o = new Fl_Box(25, 165, 365, 50, "This program is distributed under the terms of the\nGNU General Public Licens\
e Version 2.\n(Please read the file \'COPYING\' for details).");
      o->labelsize(12);
      o->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
    }
    { Fl_Box* o = new Fl_Box(25, 215, 385, 65, "This program uses the \"zlib\" library to write PNG files.\nMore info on zlib\
: http://www.zlib.org/\nQuat also uses FLTK (Fast Light Tool Kit) for its user\
 interface.\nMore info on FLTK: http://www.fltk.org/");
      o->labelsize(12);
      o->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
    }
    { Fl_Box* o = note = new Fl_Box(25, 280, 390, 20);
      o->labelsize(12);
      o->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
    }
    { Fl_Return_Button* o = ok_button = new Fl_Return_Button(155, 310, 115, 25, "OK");
      o->labelsize(12);
      o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    }
    { PixWid* o = icon = new PixWid(30, 5, 115, 105);
      o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    }
    o->set_modal();
    o->end();
  }
  icon->setPixmap(icon_xpm);
}

void AboutBox::run() {
  win->show();
while (win->shown())
{
	Fl::wait();
	for (;;) 
	{
		Fl_Widget *o = Fl::readqueue();
		if (!o) break;
		if (o == ok_button) win->hide();
	}
}
}

AboutBox::~AboutBox() {
  delete win;
}
